version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ums_user       # your DB username
      POSTGRES_PASSWORD: ums_pass   # your DB password
      POSTGRES_DB: ums_dev          # your DB name
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:





